version: '3.9'

services:
  voice-ai-fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: voice-ai-fastapi
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    volumes:
      - .:/app
    restart: unless-stopped

  voice-ai-streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: voice-ai-streamlit
    command: bash -c "cd /app && streamlit run ui/streamlit_app.py --server.port=8501 --server.address=0.0.0.0"
    ports:
      - "8501:8501"
    env_file:
      - .env.docker
    volumes:
      - .:/app
    depends_on:
      - voice-ai-fastapi
    restart: unless-stopped
